name: CI

on:
  pull_request

permissions:
  contents: read

jobs:
  build:
    name: "Build & Test"
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # required for Takumi Guard OIDC
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Takumi Guard npm registry
      uses: flatt-security/setup-takumi-guard-npm@9a5d797c2085b6326d3a2985c08e3a114b9b88c1 #v1.1.1
      with:
        bot-id: "BT01KSPTTXMY1DBFSFFSHVGJT8KA"

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Enable Corepack
      run: corepack enable

    - name: Install dependencies
      run: yarn install

    - name: Lint
      run: yarn lint 
    
    - name: Build
      run: yarn build

    - name: Test
      run: yarn test
